### ISSUE TITLE
Support GitHub Enterprise Edition

### ISSUE THREAD

**Issue by hbetts** [conventional-changelog/conventional-github-releaser#11]
Looking through the source code, it seems that I cannot pass a `host` value to the `node-github` constructor to specify a GitHub Enterprise host.

**Comment by stevemao** [comment]
I have no idea about Enterprise Edition :(

PR welcome

**Comment by hbetts** [comment]
@stevemao an example of configuring `node-github` with a custom GitHub end-point (required for interfacing with a GitHub Enterprise Edition instance), can see seen in their [Readme Example](https://github.com/mikedeboer/node-github#example).

However, I'm not entirely sure how to pass that information into the module exported by this package. Your module takes an `auth` object as the first argument. Perhaps, instead of `auth`, you could take an options object that contains a sub-object for authentication credentials, and a property for the GitHub EE information?

That seems more inline with the pattern of the other `conventional-changelog` packages.

If we went that direction, we would still need to decide what form to pass in GitHub EE information.

One way would be to allow users to pass in an object in the form expected by the `node-github` constructor. Another approach would be to have the consumer pass in the API URL for their GitHub EE instance, and parse that URL into its component parts that we could then pass into the `node-github` constructor.

The latter approach is how it's done in `semantic-release`, and how I handled GitHub EE before switching to `conventional-github-releaser`: https://github.com/hbetts/semantic-release-github-releaser/blob/e057620dc0085c43794a54ee62032c5d6772d7cd/src/index.js#L14

Mind if I get your thoughts on which approach to take?

**Comment by stevemao** [comment]
@hbetts I have no idea :( as long as there are tests to support the changes I'm fine.

**Comment by thiagofelix** [comment]
Hi @hbetts  @stevemao 
Is there any decision regarding how we expose GitHub EE params? 

Would it be ok to add more a couple of params to node-github?
- github-version ( default '3.0.0' )
- github-address ( default https://github.com )
- github-path-prefix ( default '/api/v3' )

Or perhaps even make it that every github-* prefixed param is automatically send to node-githu?

Thanks.

**Comment by hbetts** [comment]
I this this issue has been resolved.

**Comment by hbetts** [comment]
It turns out Enterprise support was not available from the CLI, even though users could connect to a GitHub Enterprise instance using the API.

Re-opening so that we can properly close the issue with pull request #49
