### ISSUE TITLE
Not compatible with git-flow tagging

### ISSUE THREAD

**Issue by tlimpanont** [conventional-changelog/conventional-github-releaser#21]
It seems like when working with git-flow and the way git flow tags the commits, the release doesn't seems to work. 

Tagging manually works fine!

It's there a different the way git-flow tags and manual tag?

**Comment by stevemao** [comment]
So you are not tagging on the branch you are releasing from?

**Comment by tlimpanont** [comment]
So to answer your question `So you are not tagging on the branch you are releasing from?`

git flow release finish tag it on the `master` branch

**Comment by stevemao** [comment]
You can change the settings in git-raw-commits to get the commits you want.

**Comment by stevemao** [comment]
@bcoe @nexdrew incase you guys have better idea?

**Comment by nexdrew** [comment]
@tlimpanont Are you running `conventional-github-releaser` from the `develop` branch or from the `master` branch?

**Comment by tlimpanont** [comment]
`master`

**Comment by nexdrew** [comment]
Hmm, sounds like a bug to me, since the tag commit should exist on the master branch history. I think we need to dig deeper to find where it's going wrong.

**Comment by stevemao** [comment]
So the tag is on the master branch?

After debugging (using `-v` flag), I found out that 

```
$ git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n'------------------------ >8 ------------------------' v0.1.0 --no-merges
docs(CHANGELOG.md): v0.1.0

-hash-
06863f437d431b32a3324d44d40edb838d30e766
-gitTags-

-committerDate-
2016-07-28 14:02:29 +0200
------------------------ >8 ------------------------
feat(application): application works

-hash-
6d169927cacbe8d9ec9eed48de02943ffeb64762
-gitTags-

-committerDate-
2016-07-28 13:57:56 +0200
------------------------ >8 ------------------------
Initial commit

-hash-
716b187d04183b129a200b9d54068e1645722c0c
-gitTags-

-committerDate-
2016-07-28 13:55:56 +0200
------------------------ >8 ------------------------
```

You are tagging on the merge commit. By default we don't include merge commits. You can either tag on non merge commits or change your config to include merge commits:

```
$ git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n'------------------------ >8 ------------------------' v0.1.0
Merge branch 'release/v0.1.0'

-hash-
d9d1e4cc34ca70e1439efe36adbc1c4940e19edd
-gitTags-
 (HEAD -> master, tag: v0.1.0, origin/master, origin/HEAD)
-committerDate-
2016-07-28 14:03:07 +0200
------------------------ >8 ------------------------
docs(CHANGELOG.md): v0.1.0

-hash-
06863f437d431b32a3324d44d40edb838d30e766
-gitTags-

-committerDate-
2016-07-28 14:02:29 +0200
------------------------ >8 ------------------------
feat(application): application works

-hash-
6d169927cacbe8d9ec9eed48de02943ffeb64762
-gitTags-

-committerDate-
2016-07-28 13:57:56 +0200
------------------------ >8 ------------------------
Initial commit

-hash-
716b187d04183b129a200b9d54068e1645722c0c
-gitTags-

-committerDate-
2016-07-28 13:55:56 +0200
------------------------ >8 ------------------------
```

**Comment by tlimpanont** [comment]
Check! Indeed that's what I found out recently tagging on the commit branch. Thanks guys!

**Comment by tlimpanont** [comment]
Can you me example code how to enable including merge commits?
