### ISSUE TITLE
Generating Changelog When Multiple Tags Available

### ISSUE THREAD

**Issue by hbetts** [conventional-changelog/conventional-github-releaser#25]
For the past month I've been looking into an issue that was filed against [semantic-release-gitlab-notifier](https://www.npmjs.com/package/semantic-release-gitlab-notifier) by @bahmutov - https://gitlab.com/hutson/semantic-release-gitlab-notifier/issues/1

@bahmutov describes a workflow where `semantic-release-gitlab` (the tool he uses for generating new releases for a GitLab-based project) is invoked only when a new tag is created on the `master` branch of his repository. His goal is to collect several commits into the `master` branch, and then, when he's ready to publish a new version of his package to the npm registry, he tags the `master` branch with a tag beginning with the word `release`.

You can see the tag pattern used to invoke the `deploy` stage of his CI pipeline [here](https://gitlab.com/hutson/batched-semantic-release/blob/master/.gitlab-ci.yml#L26).

The `semantic-release-gitlab` tool correctly generates a new version based on the commits since the last semantically valid tag, correctly ignoring the `release` tag created manually by @bahmutov.

However, when `semantic-release-gitlab` invokes `conventional-gitlab-releaser` (my fork of `conventional-github-releaser`) to generate release notes, it fails.

It comes down to the call to `conventionalChangelog`, from within `conventional-gitlab-releaser`, which fails to return a changelog. Therefore, there's nothing to post to GitLab.

Based on my testing so far, it seems the [transform](https://github.com/conventional-changelog/conventional-github-releaser/blob/73c27d93958a4cdf5ed857a3c2819ad804d7d17f/index.js#L45) function is matching against the manually created `release` tag, using the manually created `release` tag as the version of the latest commit, and that is causing `conventional-changelog-writer` to fail to generate a changelog. 

If I modify the transform function for `conventional-gitlab-releaser` to match only the semantically valid version tag created by `semantic-release-gitlab` the changelog is generated correctly, and a release note is posted to GitLab.

I have a pending merge request against `conventional-gitlab-releaser` that demonstrates the required change - https://gitlab.com/hutson/conventional-gitlab-releaser/merge_requests/1/diffs

I haven't accepted it yet because I'm not quite sure what the purpose of the `transform` function is, or whether my change is the best approach.

I wanted to get your input before proceeding.

**Comment by stevemao** [comment]
Hi @hbetts , I have sent you an invite to the team. Let me know if you need any help.

**Comment by hbetts** [comment]
Thank you @stevemao. I was able to get setup quite easily.

**Comment by hbetts** [comment]
Closed by #34
