### ISSUE TITLE
Problem when i use the angular config file

### ISSUE THREAD

**Issue by the-smaug** [conventional-changelog/conventional-github-releaser#38]
When I use the -n flag with the angular config file my release messages it doesn't work. 
My commits are not format 

I don't use the -p flag because I want to custom the angular file. 

and i got a template dir with angular templates

**Comment by hbetts** [comment]
@the-smaug, can you please re-run `conventional-github-releaser`, but include the `--verbose` flag. 

That should print out information about what `conventional-changelog` is doing.

Hopefully that flag, along with calls to `console.log` in your configuration file, will help you to determine whether you configuration is used by `conventional-changelog`, or not.

**Comment by hbetts** [comment]
@the-smaug I'm closing out this issue for now, but if you have the time to help us pursue the issue, I can reopen it.
